### PR TITLE
Extend pyenv_pip and allow user to pass envvar during installation

### PR DESCRIPTION
**Pull request by ssps**
### Description

This pull request comprises following changes.
* Allow user to install / uninstall packages in virtualenv
* Allow user to pass environment variable during pyenv and pyenv_plugin installation
* Remove 'reinstall' attribute from pyenv_pip and merge the functionality into 'options'.

As this commit breaks compatibility ('reinstall'), I'd like to hear about your opinion on it.

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by darwin67** [comment]
Thank you for the contribution!
Looks like I forgot to turn off Hound CI. I've disabled it now so could you try pushing an empty commit in order to trigger Travis?

**Comment by darwin67** [comment]
Thank you for the contribution!
There was a mistake in the CI settings that didn't trigger a build. I've updated the settings so would you mind pushing an empty commit so the Travis will run?

**Comment by darwin67** [comment]
I've also disabled Hound CI for now since it's not behaving as I want it to.

**Comment by darwin67** [comment]
Oh, and please update the CHANGELOG as well

**Comment by ssps** [comment]
Sorry, I was busy with other things.
I'll handle lint errors and do what you've suggested within few hours.

**Comment by darwin67** [comment]
LGTM! I'll create a release later today

**Pull request merged**
